-- MySQL Script generated by MySQL Workbench
-- Sat May 26 16:52:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema climbing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema climbing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climbing` DEFAULT CHARACTER SET utf8 ;
USE `climbing` ;

-- -----------------------------------------------------
-- Table `climbing`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`userType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userType_id` INT NOT NULL,
  `userId` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `grade` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nickName` VARCHAR(45) NOT NULL,
  `signupDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_userType1_idx` (`userType_id` ASC),
  CONSTRAINT `fk_user_userType1`
    FOREIGN KEY (`userType_id`)
    REFERENCES `climbing`.`userType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`boardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`boardType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `createdDate` DATE NOT NULL,
  `views` INT NOT NULL,
  `recommend` INT NOT NULL,
  `boardType_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_board_boardType1_idx` (`boardType_id` ASC),
  INDEX `fk_board_user1_idx` (`user_id` ASC),
  INDEX `fk_board_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_board_boardType1`
    FOREIGN KEY (`boardType_id`)
    REFERENCES `climbing`.`boardType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `climbing`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `climbing`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`mountian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`mountian` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mountainName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`recruitment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`recruitment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mountian_id` INT NOT NULL,
  `boardType_id` INT NOT NULL,
  `maxNum` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recruitment_mountian1_idx` (`mountian_id` ASC),
  INDEX `fk_recruitment_boardType1_idx` (`boardType_id` ASC),
  CONSTRAINT `fk_recruitment_mountian1`
    FOREIGN KEY (`mountian_id`)
    REFERENCES `climbing`.`mountian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recruitment_boardType1`
    FOREIGN KEY (`boardType_id`)
    REFERENCES `climbing`.`boardType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`mountianInfor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`mountianInfor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mountian_id` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mountianInfor_mountian1_idx` (`mountian_id` ASC),
  CONSTRAINT `fk_mountianInfor_mountian1`
    FOREIGN KEY (`mountian_id`)
    REFERENCES `climbing`.`mountian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mountian_id` INT NOT NULL,
  `boardType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_mountian_idx` (`mountian_id` ASC),
  INDEX `fk_review_boardType1_idx` (`boardType_id` ASC),
  CONSTRAINT `fk_review_mountian`
    FOREIGN KEY (`mountian_id`)
    REFERENCES `climbing`.`mountian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_boardType1`
    FOREIGN KEY (`boardType_id`)
    REFERENCES `climbing`.`boardType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(200) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `climbing`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`apply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recruitment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apply_recruitment1_idx` (`recruitment_id` ASC),
  INDEX `fk_apply_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_apply_recruitment1`
    FOREIGN KEY (`recruitment_id`)
    REFERENCES `climbing`.`recruitment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apply_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `climbing`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climbing`.`commentMatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climbing`.`commentMatch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentMatch_comment1_idx` (`comment_id` ASC),
  INDEX `fk_commentMatch_board1_idx` (`board_id` ASC),
  CONSTRAINT `fk_commentMatch_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `climbing`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentMatch_board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `climbing`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
